### ISSUE TITLE
steam-as-account defaults to 'gnome' instead of 'steamos'

### ISSUE THREAD

**Issue by flibitijibibo** [negativo17/steamos-compositor#2]
Wow cool GitHub I totally wanted to submit this totally empty report just by hitting the enter key

Anyway, by default the `steam` user config defaults to gnome and not steamos:

https://github.com/negativo17/steamos-compositor/blob/master/steam-as-account#L3

At the moment this makes sense because of https://github.com/ValveSoftware/steam-for-linux/issues/5413 and https://github.com/ValveSoftware/steam-for-linux/issues/5421, but once that is fixed this should probably default to 'steamos' for those configuring this to autologin at boot without having to, for example, set `autologin-session` in lightdm.conf. Just filing this for now to help me keep track of this!

**Comment by flibitijibibo** [comment]
Updated with the actual report, cool UX GitHub~ (sorry Simone)

**Comment by scaronni** [comment]
Package being reworked completely, sorry for the late response.
